services:
  - type: web
    name: flush-load-balancer
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run load-balancer
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOAD_BALANCER_STRATEGY
        value: round_robin
      # Vedant's development environment
      - key: DEVELOPER_VEDANT_SLACK_APP
        value: https://67ccbee1763c.ngrok-free.app
      - key: DEVELOPER_VEDANT_SLACK_OAUTH
        value: https://48cd19dfe492.ngrok-free.app
      - key: DEVELOPER_VEDANT_GOOGLE_SHEETS
        value: https://a2920615db6e.ngrok-free.app 